name: events

services:
  backend:
    build:
      context: ./src/
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Host=db_postgres;Database=Events;Username=postgres;Password=1
      - S3__Endpoint=http://localhost:9000
      - S3__ProxyHost=rustfs
      - S3__ProxyPort=9000
      - S3__AccessKey:rustfsadmin
      - S3__SecretKey:rustfsadmin
    depends_on:
      db_migrator:
        condition: service_completed_successfully
      s3_migrator:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy

  db_postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: Events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/18/docker

  db_migrator:
    build:
      context: ./src/
      dockerfile: Migrator.Dockerfile
    container_name: db_migrator
    restart: no
    environment:
      - ConnectionStrings__DbConnection=Host=db_postgres;Database=Events;Username=postgres;Password=1
    depends_on:
      db_postgres:
        condition: service_healthy

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ADDRESS=:9000
      - RUSTFS_CONSOLE_ADDRESS=:9001
      - RUSTFS_VOLUMES:/data
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - rustfs:/data
  
  s3_migrator:
    build:
      context: ./src/
      dockerfile: S3Migrator.Dockerfile
    container_name: s3_migrator
    restart: no
    environment:
      - S3__Endpoint=http://rustfs:9000
      - S3__AccessKey:rustfsadmin
      - S3__SecretKey:rustfsadmin
    depends_on:
      rustfs:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:latest-alpine
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9002:9002"
    environment:
      CLICKHOUSE_DB: Events
      CLICKHOUSE_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--port", "9002", "--query", "SELECT 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ./configs/clickhouse/ports.yaml:/etc/clickhouse-server/config.d/ports.yaml
  
  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    command:
      - --config=/etc/otelcol-contrib/otel-collector-config.yaml
    ports:
      - "4318:4318"
    volumes:
      - ./configs/otel/otel-collector-config.yaml:/etc/otelcol-contrib/otel-collector-config.yaml
    depends_on:
      clickhouse:
        condition: service_healthy

volumes:
  pg_data:
    driver: local
  rustfs:
    driver: local
  clickhouse_data:
    driver: local