// <auto-generated />
using System;
using Events.Hosts.DbMigrator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Events.Hosts.DbMigrator.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260214073741_RenameEventTypeToType")]
    partial class RenameEventTypeToType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Announcement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsRegistration")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PreviewFilename")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("TypeId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.EventFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventsFormats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Онлайн"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Офлайн"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Гибрид"
                        });
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("EventsTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Title = "Концерт"
                        },
                        new
                        {
                            Id = 1,
                            Title = "Конференция"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Митап"
                        });
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.HasOne("Events.Domain.Aggregates.EventAggregate.EventFormat", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Events.Domain.Aggregates.EventAggregate.EventType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
