// <auto-generated />
using System;
using Events.Hosts.DbMigrator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Events.Hosts.DbMigrator.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260320133049_AddedPlacesPhotos")]
    partial class AddedPlacesPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsRegistration")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("PlaceholderFilename")
                        .HasColumnType("text");

                    b.Property<string>("PreviewFilename")
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.EventFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventsFormats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Онлайн"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Офлайн"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Гибрид"
                        });
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("EventsTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Title = "Концерт"
                        },
                        new
                        {
                            Id = 1,
                            Title = "Конференция"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Митап"
                        });
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.ValueObjects.EventParticipant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("Events.Domain.Aggregates.LocationAggregate.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Events.Domain.Aggregates.LocationAggregate.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TypeId");

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("Events.Domain.Aggregates.LocationAggregate.PlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlacesTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Коворкинг"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Конференц-зал"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Аудитория"
                        });
                });

            modelBuilder.Entity("Events.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarFilename")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Events.Domain.Aggregates.UserAggregate.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("UsersRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Пользователь"
                        });
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.HasOne("Events.Domain.Aggregates.EventAggregate.EventFormat", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Events.Domain.Aggregates.LocationAggregate.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Events.Domain.Aggregates.EventAggregate.EventType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Events.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Events.Domain.Aggregates.EventAggregate.ValueObjects.EventAnnouncement", "Announcement", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Announcement");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.EventAggregate.ValueObjects.EventDateTimeRange", "DateTimeRange", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndDateTime");

                            b1.Property<DateTimeOffset>("StartDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartDateTime");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.EventAggregate.ValueObjects.EventDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Description");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.EventAggregate.ValueObjects.EventTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("Title");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Announcement")
                        .IsRequired();

                    b.Navigation("DateTimeRange")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Format");

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.ValueObjects.EventParticipant", b =>
                {
                    b.HasOne("Events.Domain.Aggregates.EventAggregate.Event", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Events.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Events.Domain.Aggregates.LocationAggregate.Location", b =>
                {
                    b.OwnsMany("Events.Domain.Shared.ValueObjects.OrderedPhoto", "Photos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Filename")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Filename");

                            b1.Property<int>("LocationId")
                                .HasColumnType("integer");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("Order");

                            b1.HasKey("Id");

                            b1.HasIndex("LocationId");

                            b1.ToTable("LocationsPhotos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.LocationAggregate.ValueObjects.Locations.LocationAddress", "Address", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Address");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.LocationAggregate.ValueObjects.Locations.LocationTitle", "Title", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Title");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Photos");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Events.Domain.Aggregates.LocationAggregate.Place", b =>
                {
                    b.HasOne("Events.Domain.Aggregates.LocationAggregate.Location", null)
                        .WithMany("Places")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Events.Domain.Aggregates.LocationAggregate.PlaceType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Events.Domain.Shared.ValueObjects.OrderedPhoto", "Photos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Filename")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Filename");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("Order");

                            b1.Property<int>("PlaceId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PlaceId");

                            b1.ToTable("PlacesPhotos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.LocationAggregate.ValueObjects.Places.PlaceCapacity", "Capacity", b1 =>
                        {
                            b1.Property<int>("PlaceId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Capacity");

                            b1.HasKey("PlaceId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.LocationAggregate.ValueObjects.Places.PlaceNumber", "Number", b1 =>
                        {
                            b1.Property<int>("PlaceId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("Number");

                            b1.HasKey("PlaceId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.OwnsOne("Events.Domain.Aggregates.LocationAggregate.ValueObjects.Places.PlaceTitle", "Title", b1 =>
                        {
                            b1.Property<int>("PlaceId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Title");

                            b1.HasKey("PlaceId");

                            b1.ToTable("Places");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();

                    b.Navigation("Photos");

                    b.Navigation("Title");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Events.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.HasOne("Events.Domain.Aggregates.UserAggregate.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Events.Domain.Aggregates.UserAggregate.ValueObjects.PersonName", "PersonName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("LastName");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Patronymic");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Events.Domain.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Events.Domain.Shared.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("PersonName")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Events.Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Events.Domain.Aggregates.LocationAggregate.Location", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
