<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Application\Events.Application.Services\Events.Application.Services.csproj"/>
        <ProjectReference Include="..\..\Infrastructure\Events.Infrastructure.DataAccess\Events.Infrastructure.DataAccess.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.19" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.13.9" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
    </ItemGroup>

</Project>
