<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Events.Hosts.S3Migrator-1b06939c-0fe1-4f6f-8987-301a12193242</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.18.3"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Application\Events.Application.Services\Events.Application.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>
