<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="9.3.1"/>
        <PackageReference Include="AutoMapper" Version="16.1.1"/>
        <PackageReference Include="AWSSDK.S3" Version="4.0.19"/>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="MediatR" Version="14.1.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5"/>
        <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" Version="2.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Contracts\Events.Contracts\Events.Contracts.csproj"/>
        <ProjectReference Include="..\..\Domain\Events.Domain\Events.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Features\Files\Placeholders\"/>
    </ItemGroup>

</Project>
