<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
        <PackageReference Include="AutoMapper" Version="16.0.0"/>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageReference Include="MediatR" Version="14.0.0"/>
        <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" Version="1.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Contracts\Events.Contracts\Events.Contracts.csproj"/>
        <ProjectReference Include="..\..\Domain\Events.Domain\Events.Domain.csproj"/>
    </ItemGroup>

</Project>
